# Generated by Django 5.2.7 on 2026-01-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='theme',
            field=models.CharField(choices=[('GENERIC', 'Genérico (Rápido)'), ('MICROSOFT', 'Microsoft 365 (Seguridad)'), ('GOOGLE', 'Google Workspace (Alerta)')], default='GENERIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template_content',
            field=models.TextField(blank=True, help_text='HTML content of the email'),
        ),
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
